#8 보호자도메인CRUD
kakao-tech-campus-2nd-step3/Team13_BE pull request #15
Opened 2024-09-22 08:56 UTC by hyyyh0x

## 🔥 관련 이슈
#8 보호자 도메인
close: #8 

## 📝 작업 상세 설명
보호자 도메인과 관리자가 보호자를 CRUD하는 부분입니다.

## ⭐ 리뷰 요구 사항
추가할 부분, 수정할 부분 보고 알려주세요!

2024-09-22 09:42 UTC, 20jcode requested changes

2024-09-22 09:42 UTC, 20jcode commented on src/main/java/dbdr/domain/guardians/Guardians.java
전화번호를 unique로 하더라도 pk로 Id는 있는게 좋지않나용?

2024-09-22 09:42 UTC, 20jcode commented on src/main/java/dbdr/domain/guardians/GuardiansResponse.java
> +    @Comment("삭제 여부") boolean isActive) {
Response에 삭제 여부는 불필요할 것 같아용... 어떠신지용...?

2024-09-22 09:42 UTC, 20jcode commented on src/main/java/dbdr/domain/guardians/GuardiansService.java
> +    @Comment("보호자 아이디로 조회하기")
여기서 ID가 그럼 전화번호를 뜻하는 것인가요?!

2024-09-22 09:46 UTC, hyyyh0x commented on src/main/java/dbdr/domain/guardians/Guardians.java
BaseEntity에 id가 있어요!

2024-09-22 09:46 UTC, hyyyh0x commented on src/main/java/dbdr/domain/guardians/GuardiansService.java
> +    @Comment("보호자 아이디로 조회하기")
BaseEntity에 있는 id를 뜻합니다

2024-09-22 09:49 UTC, hyyyh0x commented on src/main/java/dbdr/domain/guardians/GuardiansResponse.java
> +    @Comment("삭제 여부") boolean isActive) {
관리자 컨트롤러에서 전부 조회할 때 삭제되었는지 안되었는지 헷갈려서 일부러 넣어뒀는데, 필요없다고 판단되면 지우겠습니다.

2024-09-22 09:59 UTC, 20jcode commented on src/main/java/dbdr/domain/guardians/Guardians.java
설명감삼당 ㅎㅎㅎ

2024-09-22 10:01 UTC, 20jcode commented on src/main/java/dbdr/domain/guardians/GuardiansResponse.java
> +    @Comment("삭제 여부") boolean isActive) {
이건 저도 잘 모르겠네요... 나중에 회의에서 한번...?

2024-09-22 10:16 UTC, pykido requested changes
코드 리뷰 확인 부탁드립니다!!!

2024-09-22 10:16 UTC, pykido commented on src/main/java/dbdr/domain/BaseEntity.java
> +    private boolean isActive = true;
`@ColumnDefault("true")`때문에 true값을 명시적으로 지정해주지 않아도 되지 않나? 라는 생각이 들어 찾아봤습니다. 
  해당 애노테이션은 데이터베이스 레벨에서 기본값을 자동으로 지정해주는 것은 맞지만, 데이터베이스 레벨 전인 애플리케이션 단에서 객체를 생성할 때 필드 초기화 없이 만들면 자동으로 false가 된다고 하네요!!! 
  
  애플리케이션 단에서 객체 생성의 오류를 사전에 방지하신 거 짱입니다!!!

2024-09-22 10:16 UTC, pykido commented on src/main/java/dbdr/domain/guardians/AuthGuardiansController.java
> +@RequestMapping("/v1/auth/guardians")
auth의 경우 로그인/회원가입과 같이 인증, 인가에 가까운 도메인명인듯합니다! 관리자 페이지에서 사용해줄 것이기에 auth를 admin으로 바꾸는 거 어떤가요?

2024-09-22 10:16 UTC, pykido commented on src/main/java/dbdr/domain/guardians/AuthGuardiansController.java
> +    public AuthGuardiansController(GuardiansService guardiansService) {
생성자로 의존성 주입 되게 잘하셨네요!! 
 근데 저희가 Step2까지는 Lombok 사용이 허용되지 않았는데 편의를 위해 Step3부터는 사용하는게 좋겠다는 생각이 들어 추가해주었습니다! 
  따라서 `@RequiredArgsConstructor` 애노테이션 추가해주시면 자동으로 생성자주입을 해주기에 코드가 좀 더 단정해질 거 같아욤~!

2024-09-22 10:16 UTC, pykido commented on src/main/java/dbdr/domain/guardians/Guardians.java
`BaseEntity` 확인 부탁드립니당!

2024-09-22 10:16 UTC, pykido commented on src/main/java/dbdr/domain/guardians/Guardians.java
> +    public Guardians() {
기본 생성자 메서드를 만들어주신 거 같은데 아래 블로그를 참고하여 [블로그 바로가기](https://velog.io/@kevin_/%EB%82%B4%EA%B0%80-NoargsConstructor-access-AccessLevel.PROTECTED%EB%A5%BC-%EC%99%9C-%EC%9E%91%EC%84%B1%ED%96%88%EC%9D%84%EA%B9%8C) `@NoArgsConstructor(access = AccessLevel.PROTECTED)` 애노테이션을 사용해보는건 어떤가요?

2024-09-22 10:16 UTC, pykido commented on src/main/java/dbdr/domain/guardians/Guardians.java
> +    public Guardians() {
추가적으로 이 [블로그](https://cobbybb.tistory.com/14) 참고해보셔서 `Builder까지` 넣어주신다면 정말정말 아름다울 거 같습니다!!!

2024-09-22 10:16 UTC, pykido commented on src/main/java/dbdr/domain/guardians/GuardiansRequest.java
> +    @Comment("보호자 전화번호") @NotBlank(message = "전화번호를 입력하세요.") String phone,
전화번호는 무조건 `01012345678` 꼴로 들어올테니 정규식을 이용하여 이를 제어하는 것도 좋을 거 같아요~!

2024-09-22 10:17 UTC, hyyyh0x commented on src/main/java/dbdr/domain/guardians/AuthGuardiansController.java
> +@RequestMapping("/v1/auth/guardians")
좋습니다

2024-09-22 16:25 UTC, yooookm reviewed
수고하셨습니다~!

2024-09-22 16:25 UTC, yooookm commented on src/main/java/dbdr/domain/guardians/AdminGuardiansController.java
> +    @Comment("보호자 전부 조회")
Controller 함수에 `@Comment` 어노테이션을 단 이유가 있을까요??
저는 `@Comment` 어노테이션은 DB 설계 시 칼럼에 코멘트를 달기 위함이라고 알고 있어요!
혜연님이 어떤 용도로 쓰셨는지 궁금합니당!

2024-09-22 16:25 UTC, yooookm commented on src/main/java/dbdr/domain/guardians/Guardians.java
> +    @Column(nullable = false)
컬럼 속성에 글자 수 제한을 두는 것도 좋을 것 같아요!

2024-09-22 16:25 UTC, yooookm commented on src/main/java/dbdr/domain/guardians/Guardians.java
> +    @Builder
빌더 패턴 굿입니다!!

2024-09-22 16:25 UTC, yooookm commented on src/main/java/dbdr/domain/guardians/GuardiansController.java
> +    @PutMapping("/{guardianId}")
로그인한 사용자가 보호자 본인인지 검증하는 절차가 필요할 것 같아요!
단순히 api로만 아이디를 받아오면 누구나 보호자 정보를 변경할 수도 있으니까요!

2024-09-22 16:25 UTC, yooookm commented on src/main/java/dbdr/domain/guardians/GuardiansRequest.java
> +    @Comment("보호자 전화번호") @NotBlank(message = "전화번호를 입력하세요.")
어노테이션마다 개행을 해주면 가독성이 더 좋아질 듯 합니다ㅎㅎ

2024-09-22 16:25 UTC, yooookm commented on src/main/java/dbdr/domain/guardians/GuardiansResponse.java
> +    @Comment("보호자 전화번호") @NotBlank(message = "전화번호를 입력하세요.") String phone,
ExceptionHandler는 아직 구현 안 하신거죠?!
클라이언트가 message를 볼 수 있으면 좋을 것 같아요 ~

2024-09-22 16:25 UTC, yooookm commented on src/main/java/dbdr/domain/guardians/GuardiansService.java
> +            throw new Exception("존재하는 전화번호입니다.");
기본 Exception 대신 IllegalArgumentException이나 커스텀 익셉션을 사용하는 건 어떨까요??

2024-09-23 00:30 UTC, hyyyh0x commented on src/main/java/dbdr/domain/guardians/AdminGuardiansController.java
> +    @Comment("보호자 전부 조회")
이슈에 적혀있는 예시 따라서 쓰다가 막 쓰게 되었네요. 처음 사용해보는거라 용도를 잘 몰랐던 것 같아요! 검색해보고 올바른 곳에 사용하도록 하겠습니다!

2024-09-23 00:31 UTC, hyyyh0x commented on src/main/java/dbdr/domain/guardians/Guardians.java
> +    @Column(nullable = false)
좋은 생각입니다. 이름 속성에 어느 정도의 제한을 두는 것이 좋을까요?

2024-09-23 00:33 UTC, hyyyh0x commented on src/main/java/dbdr/domain/guardians/GuardiansController.java
> +    @PutMapping("/{guardianId}")
검증하는 절차는 authSecurity로 하지 않나요? 아니라면 어떤 방식으로 확인할 수 있는지 궁금합니다!

2024-09-23 00:33 UTC, hyyyh0x commented on src/main/java/dbdr/domain/guardians/GuardiansRequest.java
> +    @Comment("보호자 전화번호") @NotBlank(message = "전화번호를 입력하세요.")
넵 수정하도록 허겠습니다.

2024-09-23 00:36 UTC, hyyyh0x commented on src/main/java/dbdr/domain/guardians/GuardiansResponse.java
> +    @Comment("보호자 전화번호") @NotBlank(message = "전화번호를 입력하세요.") String phone,
네! ExceptionHandler는 충돌이 날까봐 혹시나 해서 안 만들었습니다. 나중에 회의를 거친 후 추가하는게 좋지 않을까요?

2024-09-23 00:37 UTC, hyyyh0x commented on src/main/java/dbdr/domain/guardians/GuardiansService.java
> +            throw new Exception("존재하는 전화번호입니다.");
Custom Exception은 제 마음대로 추가하면 안될 것 같다는 생각이 들었습니다! 일단 경미님 의견대로 IllegalExeption으로 변경하겠습니다.

2024-09-23 04:11 UTC, yooookm commented on src/main/java/dbdr/domain/guardians/GuardiansController.java
> +    @PutMapping("/{guardianId}")
우리가 로그인을 아직 구현하지 않은 걸 까먹었네용..

2024-09-23 05:10 UTC, mogld commented on src/main/java/dbdr/domain/chart/Chart.java
>  @SQLRestriction("isDeleted = true")
혜연님 파트는 아니긴한데.. 여기 부분도 is_active로 바꾸면 될것같아요!

2024-09-23 05:56 UTC, hyyyh0x commented on src/main/java/dbdr/domain/chart/Chart.java
>  @SQLRestriction("isDeleted = true")
수정했습니다. 알려주셔서 감사합니다!

2024-09-23 07:02 UTC, 20jcode approved these changes

2024-09-23 07:07 UTC, pykido approved these changes
굳

2024-09-23 07:08 UTC, merged