[관리자 페이지] 요양원 도메인 CRUD
kakao-tech-campus-2nd-step3/Team13_BE pull request #39
Opened 2024-09-30 00:43 UTC by hyyyh0x

## 🔥 관련 이슈

close: #9

## 📝 작업 상세 설명
- 요양원 도메인 CRUD.
- ApplicationError에 요양원 관련 에러 추가 (INSTITUTION_NOT_FOUND, DUPLICATE_INSTITUTION_NUMBER)
- logging.yml 파일에 개행이 두 번 있어 이 부분도 개행 하나로 조절하였습니다.

## ⭐ 리뷰 요구 사항

2024-09-30 06:23 UTC, pykido approved these changes
굳굳 굉장히 잘하셨숩니다~!

2024-09-30 06:23 UTC, pykido commented on src/main/java/dbdr/domain/institution/controller/InstitutionAdminController.java
> +@RequestMapping("/${spring.app.version}/admin/institution")
요거는 관리자가 사용하는 API가 아니라 개발자가 서비스 팔 떄 사용할 API라 developer로 바꾸는게 좋을 듯합니당

2024-09-30 06:23 UTC, pykido commented on src/main/java/dbdr/domain/institution/controller/InstitutionController.java
> +    public ResponseEntity<InstitutionResponse> showInstitutionInfo(@PathVariable("id") Long id) {
요것도 CRUD 작업인 듯한데 다른 컨트롤러에 두셨네요~?! 별 다른 이유가 있으신가욤!

2024-09-30 06:42 UTC, hyyyh0x commented on src/main/java/dbdr/domain/institution/controller/InstitutionController.java
> +    public ResponseEntity<InstitutionResponse> showInstitutionInfo(@PathVariable("id") Long id) {
저번에 보호자 도메인 만들 때와 같은 방식으로 만들었는데, 그때 보호자가 직접 조회와 수정을 할 수 있도록 만들어 뒀었습니다.
요양원도 그 코드를 참고해서 만들다보니 이렇게 만들었습니다! 필요없다고 생각되면 삭제 가능합니다!

2024-09-30 06:42 UTC, hyyyh0x commented on src/main/java/dbdr/domain/institution/controller/InstitutionAdminController.java
> +@RequestMapping("/${spring.app.version}/admin/institution")
넵 좋습니다 변경하겠습니다!

2024-09-30 07:15 UTC, pykido commented on src/main/java/dbdr/domain/institution/controller/InstitutionController.java
> +    public ResponseEntity<InstitutionResponse> showInstitutionInfo(@PathVariable("id") Long id) {
아하아하 필요 없는건 아닌디 요양원 도메인은 개발자만 쓸거같아서 한 컨트롤러 안에 둬도 될거같아요!

2024-09-30 07:43 UTC, hyyyh0x commented on src/main/java/dbdr/domain/institution/controller/InstitutionController.java
> +    public ResponseEntity<InstitutionResponse> showInstitutionInfo(@PathVariable("id") Long id) {
저는 CRUD가 InstitutionDeveloperController에 있어서 필요없다고 생각됩니다! 일단 이 컨트롤러는 삭제하였습니다.

2024-10-01 04:40 UTC, 20jcode requested changes
주말에 고생많으셨어용 ㅎㅎ 조금 늦게 리뷰하는 것 같아서 죄송합니당 ㅜ
저는 단지 의견일 뿐 별로라고 생각되시면 해결처리하고 원하시는 대로 하셔두 됩니당!!!

2024-10-01 04:40 UTC, 20jcode commented on src/main/java/dbdr/domain/institution/controller/InstitutionDeveloperController.java
> +@RequestMapping("/${spring.app.version}/developer/institution")
제 생각에는 admin이 더 맞는 느낌이 드는 것 같아요 -> 실제 서비스 제공 단계에서 새로운 계약에 의해 신규 요양원을 생성하고 관리하는 것은 개발자보다는 고객서비스 담당하는 분께서 하게 될 것 같습니다...

2024-10-01 04:40 UTC, 20jcode commented on src/main/java/dbdr/domain/institution/dto/request/InstitutionRequest.java
> +public record InstitutionRequest(
혹시 request에 비밀번호 항목을 넣는 것은 별로일까요...?

2024-10-01 04:43 UTC, hyyyh0x commented on src/main/java/dbdr/domain/institution/dto/request/InstitutionRequest.java
> +public record InstitutionRequest(
비밀번호 항목을 넣는게 맞는 것 같아요! 나중에 로그인도 해야하니.. 정확한 지적 감사합니다! 혹시 그럼 response에도 필요할까요?

2024-10-01 04:44 UTC, hyyyh0x commented on src/main/java/dbdr/domain/institution/controller/InstitutionDeveloperController.java
> +@RequestMapping("/${spring.app.version}/developer/institution")
admin부분이 요양원이 관리하는 admin이랑 겹쳐서 조금 혼동된다고 생각이 들었어요! 아니면 요양원이 관리하는 부분을 institution으로 바꾸고 developer -> admin으로 변경하는 건 어떠신가요?

2024-10-01 05:58 UTC, mogld commented on src/main/java/dbdr/domain/institution/controller/InstitutionDeveloperController.java
> +@RequestMapping("/${spring.app.version}/developer/institution")
요양원이 관리하는 admin 이라는게 어떤부분을 말씀하시는건진 정확히 잘 이해를 못했는데.. 일단 저도 developer보단 admin이 맞는 것 같아요!!

2024-10-01 06:00 UTC, mogld commented
너무 수고하셨습니당~!! 깔끔해서 이해하기 좋네용 저두 리뷰 제안만 드린거니까.. 보시고 혜연님께서 좀 더 맞다고 생각하는 방향대로 해결하시고 merge하시면 될것같습니다!!

2024-10-01 06:00 UTC, mogld approved these changes

2024-10-01 06:02 UTC, hyyyh0x commented on src/main/java/dbdr/domain/institution/controller/InstitutionDeveloperController.java
> +@RequestMapping("/${spring.app.version}/developer/institution")
넵 일단 바꿔두겠습니다! 저도 developer보단 admin이 맞을 것 같습니다. 요양원이 관리하는 admin은 다음 회의 때 말씀드릴게요!

2024-10-01 06:06 UTC, hyyyh0x commented on src/main/java/dbdr/domain/institution/dto/request/InstitutionRequest.java
> +public record InstitutionRequest(
앗 다시 생각해보니 그럼 CRUD할 때마다 요양원 비밀번호를 넣어줘야해서... 불편하지 않을까요? 로그인 때문이시라면 따로 로그인 request를 만드는게 어떤가 싶습니다!

2024-10-01 06:06 UTC, 20jcode commented on src/main/java/dbdr/domain/institution/controller/InstitutionDeveloperController.java
> +@RequestMapping("/${spring.app.version}/developer/institution")
이게 요양원 관리자측에서 요양 보호사 신규등록 혹은 보호자신규등록 등을 진행하는 담당자를 요양원 관리 admin이라고 하신거라면 --> 말씀하신대로 institution으로 표현하는 것이 좋은 것 같아용

2024-10-01 06:08 UTC, hyyyh0x commented on src/main/java/dbdr/domain/institution/controller/InstitutionDeveloperController.java
> +@RequestMapping("/${spring.app.version}/developer/institution")
넵 좋습니다!

2024-10-01 06:11 UTC, 20jcode commented on src/main/java/dbdr/domain/institution/dto/request/InstitutionRequest.java
> +public record InstitutionRequest(
응답에는 비밀번호를 알려주는 case는 없을 것 같아요!!

아직 비밀번호 부분이 merge되지 않아서 충분히 잊어먹을 수 있는 것 같습니당... ~ 제가 빨리 완성시키겠습니닷!

2024-10-01 06:12 UTC, 20jcode approved these changes

2024-10-01 06:14 UTC, merged