돌봄대상자/보호자/요양보호사 데이터 파일 입출력 기능 구현
kakao-tech-campus-2nd-step3/Team13_BE pull request #44
Opened 2024-10-03 15:55 UTC by mogld

## 🔥 관련 이슈

close: #34 

## 📝 작업 상세 설명

- 요양원에서는 관리해야하는 사람들이 많으니까 우선 간단한 기본정보들만으로도 정보추가할 수 있도록 설정하는게 맞다고 생각해서 관리자가 정보추가하는 항목들은 다음과 같이 선택하였습니다.
1. 요양보호사(Careworker): name, phone
2. 보호자(guardian): phone, name
3. 돌봄대상자(recipient): name, birth, carenumber)

너무 적은것같다고 생각하실수도 있는데 어짜피 상세한 필수항목들은 나중에 본인이 직접 (돌봄대상자의 경우는 당연히 요양보호사가!) 정보추가를 하면된다고 우선 생각했습니다!

- 요양보호사와 보호자는 phone으로, 돌봄대상자는 carenumber로 중복처리 검사가 진행됩니다.

- 기존 DB에 있는 정보들과, 업로드되는 엑셀파일의 정보들 모두 포함해서 중복검사하도록 코드작성하였습니다.

- 기존 DB에 같이 정보를 저장하게 되는 것이기 때문에! 첫 정보추가항목에 들어가지 않는 필드들은 nullable 허용하도록 엔티티에서 변경하였습니다. 

- 포스트맨으로 테스트 검증 완료하였습니다.

## ⭐ 리뷰 요구 사항
엑셀이랑 싸우다가 정말 화가 많이났는데요!?ㅎㅎㅎㅎㅎ

![image](https://github.com/user-attachments/assets/25eb7b6f-437a-4cfc-9c0c-fe833aa2a140)

지금 분명 코드에서도 휴대폰번호는 "텍스트형식으로", 생년월일은 "날짜형식"으로 지정을 해놨기 때문에 위 사진처럼 해당열을 전체 선택하게 되면 오른쪽끝에서 보이는 것처럼 "텍스트"형식이라고 분명히 뜬단말이죠?

![image](https://github.com/user-attachments/assets/938aa459-5242-4787-9a56-1ae04dafc77e)

그런데 정보입력하려고 해당'칸'을 선택하면 보시는것처럼 다시 "일반형식"으로 바껴서 010 이 아니고 자꾸 10이 됩니다... 왜 이런식으로 적용이되어버리는건지 이해가 안됩니다.....

그래서 일단 테스트할때는 엑셀에서 그냥 한번 더 해당열 선택후 텍스트형식버튼누르고 잘 진행했습니다. 

![image](https://github.com/user-attachments/assets/ee78d016-5c70-4951-958f-c13157f506f6)

중복검증도 잘 되구요!

결론은 지금 텍스트형식이 문제입니다! 생년월일같은경우도 2002-02-12 이런식으로 입력하고 엔터만 누르면 바로 "날짜"형식으로 잘 바뀌어서 괜찮을것같은데. 휴대폰번호같은경우는 결국 사용자가 직접 해당열 선택해서 텍스트형식으로 바꿔야해요.. 이 문제가 정말 안고쳐진다면 요양원관리자한테 "엑셀로 정보추가시 유의사항'이런식의 정보를 추가제공해야할것같습니다!

2024-10-04 06:59 UTC, pykido requested changes
정말 잘하셨숩니다! 텍스트 형식으로 바꾸는건 제 코드를 참고해보시면 너무 좋을 거 같아요! 
 추가적으로 힘든 부분 있으면 연락 주세욤!

2024-10-04 06:59 UTC, pykido commented on src/main/java/dbdr/domain/careworker/entity/Careworker.java
> +    @Column
엇 요거 nullable하게 만드신 이유가 있으신가욤?!

2024-10-04 06:59 UTC, pykido commented on src/main/java/dbdr/domain/excel/dto/FileDataResponseDto.java
> +    public FileDataResponseDto(String name, String phone) {
한 DTO 안에서 처리한 거 되게 잘하신 거 같아욤!

2024-10-04 06:59 UTC, pykido commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +    public byte[] generateCareworkerTemplate() {
파일 다운로드 부분의 경우 제 코드랑 비교해보실래요? 저는 아래와 같은 방식으로 구현하였는데 텍스트 형식으로 잘 바뀌더라구요!!
 
 ```
 public byte[] generateCustomerExcelTemplate() {
		try (Workbook workbook = new XSSFWorkbook()) {
			Sheet sheet = workbook.createSheet("Customers");
			sheet.setDefaultColumnWidth(28);
			setCellStyleText(workbook, sheet, 5);
			createHeader(workbook, sheet);
			createSampleData(sheet);
			return convertWorkbookToByteArray(workbook);
		} catch (IOException e) {
			throw new ApplicationException(ApplicationError.FILE_DOWNLOAD_ERROR);
		}
	}

	private void createHeader(Workbook workbook, Sheet sheet) {
		Row headerRow = sheet.createRow(0);
		String[] headerNames = {"primary_car_number", "visit_count", "cancel_count", "name", "memo", "telephone"};
		CellStyle headerCellStyle = createHeaderCellStyle(workbook);
		for (int i = 0; i < headerNames.length; i++) {
			Cell headerCell = headerRow.createCell(i);
			headerCell.setCellValue(headerNames[i]);
			headerCell.setCellStyle(headerCellStyle);
		}
	}

	public void setCellStyleText(Workbook workbook, Sheet sheet, int index) {
		XSSFCellStyle style = (XSSFCellStyle) workbook.createCellStyle();
		XSSFDataFormat xssfDataFormat = (XSSFDataFormat) workbook.createDataFormat();
		style.setDataFormat(xssfDataFormat.getFormat("@"));
		sheet.setDefaultColumnStyle(index, style);
	}

	private void createSampleData(Sheet sheet) {
		String[][] sampleData = {
			{"456로5678", "0", "0", "홍길동", "단골 고객", "01012345678"},
		};
		for (int i = 0; i < sampleData.length; i++) {
			Row bodyRow = sheet.createRow(i + 1);
			for (int j = 0; j < sampleData[i].length; j++) {
				Cell bodyCell = bodyRow.createCell(j);
				bodyCell.setCellValue(sampleData[i][j]);
			}
		}
	}

	private CellStyle createHeaderCellStyle(Workbook workbook) {
		XSSFFont headerFont = (XSSFFont) workbook.createFont();
		headerFont.setColor(new XSSFColor(new byte[]{(byte) 255, (byte) 255, (byte) 255}));
		XSSFCellStyle headerCellStyle = (XSSFCellStyle) workbook.createCellStyle();
		headerCellStyle.setBorderLeft(BorderStyle.THIN);
		headerCellStyle.setBorderRight(BorderStyle.THIN);
		headerCellStyle.setBorderTop(BorderStyle.THIN);
		headerCellStyle.setBorderBottom(BorderStyle.THIN);
		headerCellStyle.setFillForegroundColor(new XSSFColor(new byte[]{(byte) 34, (byte) 37, (byte) 41}));
		headerCellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
		headerCellStyle.setFont(headerFont);
		return headerCellStyle;
	}

	private byte[] convertWorkbookToByteArray(Workbook workbook) throws IOException {
		try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
			workbook.write(outputStream);
			return outputStream.toByteArray();
		}
	}
 ```

2024-10-04 06:59 UTC, pykido commented on src/main/java/dbdr/domain/recipient/entity/Recipient.java
> +    @Column
엇 이 필드들 또한 왜 nullable하게 설정하셨나욤?

2024-10-06 10:49 UTC, mogld commented on src/main/java/dbdr/domain/careworker/entity/Careworker.java
> +    @Column
PR설명에도 적어놨듯이 그 엑셀파일정보들 또한  같은 DB에 저장되는건데 이때 저는 요양원에서 추가하는 첫 정보항목들은 2-3개정도로 한정했기 때문에! 그 항목에 해당하지 않는 값들은 nullable처리 해줘야 디비저장에 문제가 없어서 이렇게 설정했습니당

2024-10-06 11:11 UTC, mogld commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +    public byte[] generateCareworkerTemplate() {
XSSFCellStyle style = (XSSFCellStyle) workbook.createCellStyle();
   	XSSFDataFormat xssfDataFormat = (XSSFDataFormat) workbook.createDataFormat();
   	style.setDataFormat(xssfDataFormat.getFormat("@")); 정말 이거쓰니까 적용되네요!! 감사합니다!!!!

2024-10-06 23:57 UTC, hyyyh0x approved these changes
너무 수고하셨습니다!

2024-10-06 23:57 UTC, hyyyh0x commented on src/main/java/dbdr/domain/excel/controller/ExcelController.java
> +    @GetMapping("/careworker/download")
getmapping인데 download와 upload라는 말이 꼭 필요할까요? 개인적인 의견입니다!

2024-10-06 23:57 UTC, hyyyh0x commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +                } catch (ApplicationException e) {
catch문에서 새롭게 에러 메시지나 관련해서 알려주는 항목이 없네요! 의도하신 것인지 궁금합니다!

2024-10-07 01:15 UTC, mogld commented on src/main/java/dbdr/domain/excel/controller/ExcelController.java
> +    @GetMapping("/careworker/download")
음 저는 우선 API가 명확한 의미를 가지는게 좋겠다라고 생각해서 저렇게 하긴헸는데.. 요부분은 앞으로 고도화시키면서 고민해보겠습니당!

2024-10-07 01:22 UTC, mogld commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +                } catch (ApplicationException e) {
네 맞아요! 의도한겁니다! 예외가 발생하더라도 중단시키지 않고 실패한 항목을 faileddata리스트에 기록하는 방식으로 처리했습니당

2024-10-07 05:06 UTC, 20jcode reviewed
수고하셨습니당....
너무 늦?게 리뷰하는 것 같아 죄송한 마음 한스푼...
낮선 라이브러리에 고생 하셨을 것 같아 공감 한스푼...

넣어서 리뷰했습니다!

근데 이건 진짜 진짜 약간의 스타일차이인 것 같은데 (제가 틀린방법일 수 있음)
서비스 class를 조금만 나누어주시면?? 어떠신지...? 조심스럽게 여쭤봅니다...

제가 아직 실력이 부족해서 그런가... 약간 길어서 뭔가 조금 어려운?? 느낌이 나더라구요...

만약에 제가 여기서 careworker에 새로운 필드를 추가해서 엑셀로 작업하는 기능을 추가한다면... (ex : 근무시작일?, 성별?) 
초큼 시간이 많이 걸릴 것 같은 느낌....?

근데 진짜 단순한 제 생각이라서... 무시하셔두 됩니닷!!

2024-10-07 05:06 UTC, 20jcode commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +    public byte[] generateCareworkerTemplate() {
템플릿을 만들 때 해당 값들을 능동적?으로 변경할 수 있으면 좋을 것 같아요!!

예를 들어 careworker를 추가하기 위한 excel 부분이라면, 현재 careworker repository에 있는 
field 명을 조회해서 해당 부분을 채워준다던지??

2024-10-07 05:06 UTC, 20jcode commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +public class ExcelService {
서비스 메소드에 @Transactional 어노테이션을 적용할 필요는 없나요?!!

2024-10-07 05:06 UTC, 20jcode commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +    private void createHeaderRow(Sheet sheet, String... headers) {
요부분은 steam으로 표현은 별루인가요?

2024-10-07 05:06 UTC, 20jcode commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
try-with-resources 잘배우고갑니닷

2024-10-07 05:06 UTC, 20jcode commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +    private FileUploadResponseDto processExcelFile(MultipartFile file, RowProcessor rowProcessor) {
다운로드와 업로드를 서로 다른 서비스 파일로 분리하는건 별루인가요?!

(진짜 생각입니다) : 뭔가 서로 같은 엑셀을 대상으로 하지만 역할이 좀 많이 다른 것 같은 느낌?!

2024-10-07 06:08 UTC, mogld commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +    private FileUploadResponseDto processExcelFile(MultipartFile file, RowProcessor rowProcessor) {
오오 아니에요 저도 서비스파일 너무 길다고는 생각했어서... 적용하겠습니다!!

2024-10-07 06:13 UTC, mogld commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +    public byte[] generateCareworkerTemplate() {
음.. 제가 이해한바가 맞는지 모르겠는데 필드값을 능동적으로 추가하면 좋겠다는 말씀 맞을까요??
예를들어서 지금 careworker의 고정 필드가  이름, 번호인데 이걸 repository에 있는 필드들 중에 또 추가하고 싶다는..??
근데 만약 말씀하신게 이게맞다면.. 저희가 엑셀파일템플릿형식하고 프론트쪽에서 추가예정인 요양원의 정보추가화면의 필드값이 똑같아야 되는것 아닌가용...??

2024-10-07 07:38 UTC, mogld commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +public class ExcelService {
엇 필요할 것 같아요!! 감사합니당~~

2024-10-07 11:14 UTC, 20jcode commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +    private FileUploadResponseDto processExcelFile(MultipartFile file, RowProcessor rowProcessor) {
감사합니당 ㅎㅎ; (꾸벅하는 이모티콘)

2024-10-07 11:24 UTC, 20jcode commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +    public byte[] generateCareworkerTemplate() {
약간 변화에 대응할 수 있는? 그런 느낌으로 저는 생각해서 말씀드려봤어용 ㅎㅎㅎ....
지금은 고정값이 2개인데 만약에 새로운 필드를 하나 추가하게된다면 entity + 서비스들 코드를 전부 수정하면서 동시에 excel 입출력 부분도 수정해야하는데 복잡도가 너무 높은?? 느낌이라서요...

그래서 그렇게 되면 좋을 것 같다....하는 느낌? 입니닷...


---
번외로 혹시 careworker에 institutionId 부분은 어디서 처리되는지욧...?

2024-10-07 11:26 UTC, 20jcode commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +                } catch (ApplicationException e) {
이부분 솔직히 멋졌어요

2024-10-07 12:02 UTC, mogld commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +    public byte[] generateCareworkerTemplate() {
아하... 그렇긴하네요ㅠㅜㅜ 이부분도 그럼 이번에 수정하면서 한번 같이!! 고쳐보겠습니당   institutionId가 그때 요양원이랑 요양보호사 mapping한다는 생각으로 만들어놨는데......아직 쓰임이..ㅎ

2024-10-07 12:14 UTC, mogld commented on src/main/java/dbdr/domain/excel/service/ExcelService.java
> +                } catch (ApplicationException e) {
ㅋㅋㅋㅋㅋㅋ 이게 다... 상세한 이슈설명의 도움덕분.... 그저 감사를.....표합니다

2024-10-10 03:28 UTC, closed without merging